baseURL = "https://www.wiktordyngosz.pl"
languageCode = "en-us"
title = "Wiktor Dyngosz"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-134763748-1"

# Google SEO
enableRobotsTXT = true
canonifyURLs = true

# Uncomment below to enable syntax highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    pre = "edit"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  includeBootstrapJs = false
  showActiveNav = true
  dateFormat = "Jan 2, 2006"
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false

[params.contact]
    email = "wiktor.dyngosz@gmail.com"
    twitter = "WiktorDyngosz"
    linkedin = "https://www.linkedin.com/in/wiktordyngosz/"
    github = "dyngosz"

[params.about]
    enable = true
    subtitle = "Hi, I'm Wiktor"
    subtitle2 = "Java Dev & Salesforce Consultant" 
    subtitle3 = "Based in Wrocław, Poland"
    aboutMe = ["**Currently working as Salesforce Consultant at [<img class=logo src=images/vm.png>](https://www.vm.pl/)**",
    "Over 5 years of experience in IT world. Always eager to learn, always keen to help. ",
    "Lately focused mostly on crafting beautiful Lightning components and working my way up towards Salesforce Certifications. Remote work enthusiast. A chronic perfectionist. In my spare time I devour books (gotta love my Kindle) and hike every mountain range possible. ",
    "I <i class=heart-icon data-feather=heart></i> all board sports: snowboard, surfing, wake, kite (still <i>ToDo</i>) and [splitboard](https://www.nonstopsnow.com/journal/what-is-splitboarding).",
    "I also write [a bit](/post/)."]
