baseURL = "https://www.wiktordyngosz.pl"
languageCode = "en-us"
title = "Wiktor Dyngosz"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-134763748-1"

# Uncomment below to enable syntax highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    pre = "edit"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  includeBootstrapJs = false
  showActiveNav = true
  dateFormat = "Jan 2, 2006"
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false

[params.contact]
    email = "wiktor.dyngosz@gmail.com"
    twitter = "WiktorDyngosz"
    linkedin = "https://www.linkedin.com/in/wiktordyngosz/"
    github = "dyngosz"

[params.about]
    enable = true
    subtitle = "Hi, I'm Wiktor"
    subtitle2 = "Java Developer from Wrocław, Poland."
    aboutMe = ["**Currently working as Java Dev at [<img class=codibly-logo src=images/codibly.png>](https://www.codibly.com/).**",
    "Over 5 years of experience in IT world. Always eager to learn, always keen to help. ",
    "Lately focused mostly on scalable microservice applications deployed with modern Java & Spring stack. Remote work enthusiast. A chronic perfectionist. In my spare time I devour books (gotta love my Kindle) and play with Python & ML. ",
    "I <i class=heart-icon data-feather=heart></i> all board sports: snowboard, surfing, wake, kite (still ToDo) and recently [splitboard](https://www.nonstopsnow.com/journal/what-is-splitboarding)."]
